# PCL people recognition model parameters
svm: "../config/people_detection_svm.yaml"

# Minimum HOG confidence variable (greater magnitude means more flexibility)
conf: -2.8

# Limits to detected person cluster size in meters
min_h: 1.4
max_h: 1.9
min_w: 0.1
max_w: 0.8

# Voxel size for data extrapolation
vox_s: 0.03

# Toggle between RGB stream in viewer and a specified solid color
use_rgb_stream: false
color: { r: 0, g: 230, b: 190 }

# Depth camera intrinsics (does influence person cluster recognition)
intrinsics: { f_x: 387.4, f_y: 387.4, ppx: 281.7, ppy: 242.2, s: 0.0 }
